[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "ls -la",
  "cd backend && npm install",
  "cd travel-planning-app && npm install",
  "cd travel-planning-app && npm run build",
  "ls -la travel-planning-app/dist"
]

[start]
cmd = "cd backend && npm start"